---
title: BlogInn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: BlogInn is a bold theme for the Jekyll blogging platform. Available for
  purchase at ThemeForest.net.
tagline: Thoughts, stories and ideas.
baseurl: 
sass:
  sass_dir: _sass
url: http://justgoodthemes.com
navigation:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Style Guides
  url: "/style-guide/"
- text: Archives
  url: "/tags/"
disqus: 
author_name: John Doe
author_bio: John is a designer, photographer, speaker, author of a couple of books
  about typography and the founder of photo magazine Curious.
author_url: http://justgoodthemes.com
author_location: Vilnius, Lithuania
author_image: "/images/authorimage.png"
banner_url: http://justgoodthemes.com
banner_image: images/banner.jpg
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
twitter_username: username
facebook_username: username
googleplus_username: "+username"
github_username: username
codepen_username: username
dribbble_uername: username
medium_username: "@username"
instagram_username: username
pinterest_username: username
linkedin_username: username
weibo_username: username
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
- jekyll-paginate
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
